### ISSUE TITLE
attached PDF file is corrupted

### ISSUE THREAD

**Issue by Nakurai** [mailgun/mailgun-js-boland#158]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.13.0

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
NodeJS 6.11.0, Windows 10 Home

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
I don't know yet

4) Sample source code or steps to reproduce
I am sending a file using the mailgun-js module in NodeJS. The original file is fine, but the one I receive is corrupted.I am using the code below to send my file. The array infos.attachements contains the path and name of the files I want to send.
```javascript
var file = fs.readFileSync(infos.attachments[0].path);
var attch = new mailgun.Attachment({data: file, filename:infos.attachments[0].name , contentType: 'application/pdf'});
var mailOptions = {
   from: 'sender address',
   to: 'receiver address',
   attachment:[attch],
   subject: 'some subject',
   text: 'text content'
};
mailgun.messages().send(mailOptions, function(error, body){...
```
Any idea what I am doing wrong?

**Comment by bojand** [comment]
Tried with Node 6.11.0 on mac OS (I do not have access to Windows easily) and this works fine for me:

```js
var filePath = path.resolve(__dirname, './pdf-sample.pdf');
var data = fs.readFileSync(filePath);
var filename = 'sample-pdf.pdf';

var attch = new mailgun.Attachment({ data, filename, contentType: 'application/pdf' });
var mailOptions = {
  to: '<to address>',
  from: '<from address>',
  subject: 'Hello testing mailgun',
  text: 'testing message for mailgun',
  attachment: [attch]
};

mailgun.messages().send(mailOptions, function (error, body) {
  if (error) console.error(error)
  console.log(body)
});
```

The request goes through without an issue. I receive an email and the pdf is attached fine and I can view the file without issues.

**Comment by Nakurai** [comment]
Thank you for answering. I don't really know what to add here. I guess the problem is related to my specific case, but I am still not sure what's happening.

**Comment by philiiiiiipp** [comment]
Hey did you try adding the knownLength ? 

`knownLength: fs.statSync(getPath(filename)).size`

**Comment by theryaz** [comment]
@Nakurai Did you ever find a solution to this?

**Comment by Nakurai** [comment]
Hello, no sorry. My requirements changed and I ended up not sending the files by email.

**Comment by theryaz** [comment]
My workaround for this is that I use `pdfinfo` to check if the pdf is valid or not before sending the email. When I validate the PDF before sending it, it never arrives corrupt. That's a good sign at least because it means the problem isn't in this module.

**Comment by dvuvne** [comment]
I am having the same issue. Any other workaround besides using pdfinfo?

**Comment by theryaz** [comment]
> I am having the same issue. Any other workaround besides using pdfinfo?

Unfortunately I haven't worked on this project for a long time, but once I put the `pdfinfo` check in place the emailed PDFs never arrived corrupt. I think I wrote code to check the PDF and re-download it if it failed the `pdfinfo` check and we never had an issue again
