### ISSUE TITLE
Sending messages CC and BCC

### ISSUE THREAD

**Issue by kdekooter** [mailgun/mailgun-js-boland#9]

**Comment by fabyeah** [comment]
@aakashlpin thanks for the tip, but that has the same effect as not specifying bcc at all. I have the same recipients in 'to' and 'bcc' and every recipient sees every other recipient's email!?

**Comment by aakashlpin** [comment]
@fabyeah that's expected right?

Here's the code snippet from my codebase that might help.

```
var mailcomposer = new MailComposer();
var message = {
    'from': ('Aakash Goel <aakash@'+ domain +'>'),
    'to': payload.to,
    'bcc': payload.bcc,
    'html': payload.html,
    'subject': payload.subject,
    'h:Reply-To': 'xxx@xxx.com'
};
mailcomposer.setMessageOption(message);
mailcomposer.buildMessage(function(mailBuildError, messageSource) {
    var dataToSend = {
        to: payload.to,
        message: messageSource,
        'h:Reply-To': xxx@xxx.com'
    };

    if (payload.bcc) {
        dataToSend.to = (payload.to + ',' + payload.bcc);
    }

    mailgun.messages().sendMime(dataToSend, function (err, responseStatus) {
        if (err) {
            callback(err);
        } else {
            callback(null, responseStatus);
        }
    });
});

**Comment by fabyeah** [comment]
@aakashlpin thanks for the reply. So your BCC recipient doesn't see other BCC recipients email adresses? For me, they do, which is not how it should be? Though 'to' and 'bcc' are the same in my case, maybe that causes the problem that there is no dedicated 'to' recipient that's not a 'bcc'.

**Comment by aakashlpin** [comment]
Ah. Now I understand your use case. The BCC for me is always just one email ID. So, yeah, maybe what you saying is what's happening.
